### PR TITLE
feat: Turned navbar logo into link to "https://www.techoptimum.org/"

### PR DESCRIPTION
**Pull request by toastdevv**

### CODE REVIEW

**Review by PranTanTheMan — APPROVED** [review]
Yes

**Comment by siddharthd0** [comment]
Screenshot 2023-08-02 at 3 34 10 PM

**Comment by siddharthd0** [comment]
@YLTN @PranTanTheMan

**Comment by toastdevv** [comment]
> Screenshot 2023-08-02 at 3 34 10 PM

oh

**Pull request merged**
